openapi: 3.0.3
info:
  title: Filo
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /vehicle/search:
    post:
      tags:
        - vehicle
      summary: Search vehicles
      operationId: vehicle_search
      parameters:
        - $ref: "#/components/parameters/XUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleListRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleListResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}:
    post:
      tags:
        - vehicle
      summary: Get vehicle by id
      operationId: vehicle_getById
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/create:
    post:
      tags:
        - vehicle
      summary: Add vehicle
      operationId: vehicle_create
      parameters:
        - $ref: "#/components/parameters/XUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleCreateRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/update:
    post:
      tags:
        - vehicle
      summary: Update vehicle
      operationId: vehicle_update
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/delete:
    post:
      tags:
        - vehicle
      summary: Delete vehicle
      operationId: vehicle_delete
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: string
          required: true

      responses:
        '200':
          description: Success
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    XUser:
      in: header
      name: 'X-User'
      required: true
      schema:
        $ref: '#/components/schemas/XUser'
  schemas:
    XUser:
      type: object
      required:
        - userId
        - companyId
        - userRole
      properties:
        userId:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        companyId:
          type: integer
          format: int64
        companyName:
          type: string
        userRole:
          $ref: '#/components/schemas/UserRole'

    UserRole:
      type: string
      enum:
        - COMPANY_ADMIN
        - STANDARD

    VehicleListRequest:
      type: object
      properties:
        from:
          type: integer
          default: 0
        size:
          type: integer
          default: 20
        term:
          type: string
        sort:
          $ref: '#/components/schemas/Sort'

    VehicleListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    VehicleCreateRequest:
      type: object
      required:
        - numberPlate
        - brand
        - model
        - modelYear
      properties:
        numberPlate:
          type: string
        chassisNumber:
          type: string
        tag:
          type: string
        brand:
          type: string
        model:
          type: string
        modelYear:
          type: integer


    Vehicle:
      type: object
      required:
        - numberPlate
        - brand
        - model
        - modelYear
      properties:
        id:
          type: string
        numberPlate:
          type: string
        chassisNumber:
          type: string
        tag:
          type: string
        brand:
          type: string
        model:
          type: string
        modelYear:
          type: integer
        creationDate:
          type: string
          format: date-time
        actionAccess:
          $ref: '#/components/schemas/VehicleActionAccess'

    VehicleActionAccess:
      type: object
      required:
        - update
        - delete
        - manageUsers
      properties:
        update:
          type: boolean
        delete:
          type: boolean
        manageUsers:
          type: boolean

    Sort:
      type: object
      properties:
        property:
          type: string
          default: CREATION_DATE
          enum:
            - CREATION_DATE
        direction:
          type: string
          default: ASC
          enum:
            - ASC
            - DESC






