openapi: 3.0.3
info:
  title: Filo
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /vehicle/search:
    post:
      tags:
        - vehicle
      summary: Search vehicles
      operationId: vehicle_search
      parameters:
        - $ref: "#/components/parameters/XUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleListRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleListResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}:
    post:
      tags:
        - vehicle
      summary: Get vehicle by id
      operationId: vehicle_getById
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/create:
    post:
      tags:
        - vehicle
      summary: Add vehicle
      operationId: vehicle_create
      parameters:
        - $ref: "#/components/parameters/XUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleCreateRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/update:
    post:
      tags:
        - vehicle
      summary: Update vehicle
      operationId: vehicle_update
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleUpdateRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/delete:
    post:
      tags:
        - vehicle
      summary: Delete vehicle
      operationId: vehicle_delete
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true

      responses:
        '200':
          description: Success
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/users/search:
    post:
      tags:
        - vehicle users
      summary: Search users on vehicle
      operationId: vehicle_searchUser
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleUserListRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleUserListResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/users/{userId}:
    post:
      tags:
        - vehicle users
      summary: Get user on vehicle
      operationId: vehicle_getUser
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: userId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/users/create:
    post:
      tags:
        - vehicle users
      summary: Create user for vehicle
      operationId: vehicle_createUser
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleUser'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/users/{userId}/update:
    post:
      tags:
        - vehicle users
      summary: Update user on vehicle
      operationId: vehicle_updateUser
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: userId
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleUserUpdateRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vehicle/{id}/users/{userId}/delete:
    post:
      tags:
        - vehicle users
      summary: Delete user on vehicle
      operationId: vehicle_deleteUser
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: userId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Success
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /group/create:
    post:
      tags:
        - group
      summary: Create group
      operationId: vehicle_createGroup
      parameters:
        - $ref: "#/components/parameters/XUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupCreateRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /group/search:
    post:
      tags:
        - group
      summary: Search group
      operationId: vehicle_searchGroup
      parameters:
        - $ref: "#/components/parameters/XUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupListRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupListResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /group/{id}:
    post:
      tags:
        - group
      summary: Get group
      operationId: vehicle_getGroup
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /group/{id}/vehicles/create:
    post:
      tags:
        - group vehicles
      summary: Create vehicle in group
      operationId: vehicle_createGroupVehicle
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupVehicleCreateRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /group/{id}/vehicles/search:
    post:
      tags:
        - group vehicles
      summary: Search vehicle in group
      operationId: vehicle_searchGroupVehicle
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupVehicleListRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupVehicleListResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /group/{id}/vehicles/{vehicleId}/delete:
    post:
      tags:
        - group vehicles
      summary: Delete vehicle in group
      operationId: vehicle_deleteGroupVehicle
      parameters:
        - $ref: "#/components/parameters/XUser"
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
        - in: path
          name: vehicleId
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupVehicleCreateRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  parameters:
    XUser:
      in: header
      name: 'X-User'
      required: true
      schema:
        $ref: '#/components/schemas/XUser'
  schemas:
    XUser:
      type: object
      required:
        - userId
        - companyId
        - userRole
      properties:
        userId:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        companyId:
          type: integer
          format: int64
        companyName:
          type: string
        userRole:
          $ref: '#/components/schemas/UserRole'

    UserRole:
      type: string
      enum:
        - COMPANY_ADMIN
        - STANDARD

    VehicleListRequest:
      type: object
      properties:
        term:
          type: string
        pageRequest:
          $ref: '#/components/schemas/PageRequest'


    VehicleListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    VehicleCreateRequest:
      type: object
      required:
        - numberPlate
        - brand
        - model
        - modelYear
      properties:
        numberPlate:
          type: string
        chassisNumber:
          type: string
        tag:
          type: string
        brand:
          type: string
        model:
          type: string
        modelYear:
          type: integer
        groupId:
          type: integer
          format: int64


    Vehicle:
      type: object
      required:
        - numberPlate
        - brand
        - model
        - modelYear
      properties:
        id:
          type: string
        numberPlate:
          type: string
        chassisNumber:
          type: string
        tag:
          type: string
        brand:
          type: string
        model:
          type: string
        modelYear:
          type: integer
        creationDate:
          type: string
          format: date-time
        actionAccess:
          $ref: '#/components/schemas/VehicleActionAccess'
        groupId:
          type: integer
          format: int64
        groupName:
          type: string

    VehicleActionAccess:
      type: object
      required:
        - update
        - delete
        - manageUsers
      properties:
        update:
          type: boolean
        delete:
          type: boolean
        manageUsers:
          type: boolean

    Sort:
      type: object
      properties:
        property:
          type: string
          default: CREATION_DATE
          enum:
            - CREATION_DATE
        direction:
          type: string
          default: ASC
          enum:
            - ASC
            - DESC

    VehicleUpdateRequest:
      type: object
      properties:
        numberPlate:
          type: string
        chassisNumber:
          type: string
        tag:
          type: string
        brand:
          type: string
        model:
          type: string
        modelYear:
          type: integer

    VehicleUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
        role:
          $ref: '#/components/schemas/UserRole'

    PageRequest:
      type: object
      properties:
        from:
          type: integer
          default: 0
        size:
          type: integer
          default: 20
        sort:
          $ref: '#/components/schemas/Sort'

    VehicleUserListRequest:
      type: object
      properties:
        userRole:
          $ref: '#/components/schemas/UserRole'
        pageRequest:
          $ref: '#/components/schemas/PageRequest'

    VehicleUserListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/VehicleUser'

    VehicleUserUpdateRequest:
      type: object
      properties:
        userRole:
          $ref: '#/components/schemas/UserRole'

    Group:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        subGroups:
          type: array
          items:
            $ref: '#/components/schemas/Group'
        vehicles:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'

    GroupCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        parentId:
          type: integer
          format: int64

    GroupListRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        pageRequest:
          $ref: '#/components/schemas/PageRequest'

    GroupListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/Group'

    GroupUpdateRequest:
      type: object
      properties:
        name:
          type: string

    GroupVehicleCreateRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64

    GroupVehicleListRequest:
      type: object
      properties:
        name:
          type: string
        subGroups:
          type: boolean
          default: false
        pageRequest:
          $ref: '#/components/schemas/PageRequest'

    GroupVehicleListResponse:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'



