spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: username
    password: passwd

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "health"