ALTER TABLE T_VEHICLE_AUTHORITY
    DROP CONSTRAINT T_VEHICLE_AUTHORITY_AUTHORIZED_VEHICLE_ID_FKEY;

ALTER TABLE T_VEHICLE_AUTHORITY
    RENAME COLUMN AUTHORIZED_VEHICLE_ID TO VEHICLE_ID;

ALTER TABLE T_VEHICLE_AUTHORITY
    ADD CONSTRAINT T_VEHICLE_VEHICLE_ID_FKEY
        FOREIGN KEY (VEHICLE_ID)
            REFERENCES T_VEHICLE (ID);